### ISSUE TITLE
Yugabyte SQL: filtering in query editor UI throws SQL error

### ISSUE THREAD

**Issue by aeberhart** [dashjoin/platform#21]
Data source: Chinook
Table: Artist

choosing filter "AC/DC" (actually any) leads to:

org.dashjoin.service.ExMapper toResponse INFO: REST exception
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "artist"
Position: 251
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
at org.dashjoin.service.SQLDatabase.getMetadata(SQLDatabase.java:680)
at org.dashjoin.service.SQLEditor.prettyPrint(SQLEditor.java:600)
at org.dashjoin.service.SQLEditor.setWhere(SQLEditor.java:263)

**Comment by aeberhart** [comment]
works now
