### ISSUE TITLE
Bundled GraalVM in Linux binaries does not find language js

### ISSUE THREAD

**Issue by uw4** [dashjoin/platform#239]
Effect:
Platform starts up and works, but Jsonata fallls back to the Java impl
Even though language is bundled in the binary, it is not found/picked up by GraalVM

Workaround:
1) Use dashjoin-jar.zip
2) Install local GraalVM with js + start platform from there

Log:
2022-11-02 16:41:28,270 WARN  [org.das.exp.jso.JsonataJS] (executor-thread-1) Fallback to Jsonata4Java - cannot create Jsonata reference instance: java.lang.IllegalArgumentException: A language with id 'js' is not installed. Installed languages are: [].
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(Unknown Source)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.throwNotInstalled(Unknown Source)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(Unknown Source)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(Unknown Source)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.lookupLanguageContext(Unknown Source)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(Unknown Source)

**Comment by uw4** [comment]
Fixed in CI build action
