### ISSUE TITLE
Error shows up when using DASHJOIN_APPURL

### ISSUE THREAD

**Issue by uw4** [dashjoin/platform#316]
Run with:
docker run --rm -p 18080:8080 -e DASHJOIN_HOME=demo -e DASHJOIN_APPURL=https://github.com/dashjoin/dashjoin-demo dashjoin/platform

Git clone functionality works, but this error shows up:

ERROR [org.ecl.jgi.uti.FS] (JGit-FileStoreAttributeWriter-2) Cannot save config file 'FileBasedConfig[/.config/jgit/config]': java.io.IOException: Creating directories for /.config/jgit failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:413)
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:140)
	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:184)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:766)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$5(FS.java:448)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by aeberhart** [comment]
https://stackoverflow.com/questions/65731005/jgit-throws-java-io-ioexception-creating-directories-for-config-jgit-failed
