### ISSUE TITLE
Strange behavior when session storage is full

### ISSUE THREAD

**Issue by uw4** [dashjoin/platform#39]
ERROR DOMException: Failed to set a named property on 'Storage': Setting the value of 'context' exceeded the quota.
    at SafeSubscriber._next (http://localhost:4200/main.js:10799:56)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.js:50169:16)
    at SafeSubscriber.next (http://localhost:4200/vendor.js:50108:22)
    at Subscriber._next (http://localhost:4200/vendor.js:50058:26)

Dev mode showed this trace:

           this.root = true;
                this.init();
                if (this.table) {
                    this.http.get(this.url).subscribe(res => {
                        // value loaded
                        if (this.database === 'config' && this.table === 'Table') {
                            // we are on a table page
                            const tmp = _util__WEBPACK_IMPORTED_MODULE_20__["Util"].parseTableID(this.pk1);
                            this.app.getSchema(tmp[1], tmp[2]).subscribe(mycache => {
                                // read myself since there might be unsaved layout edits in the app.cache
                                if (mycache.tableLayout) {
                                    this.setLayout(mycache.tableLayout, 'table', null);
                                    this.value = res;
                                    this.doLayout();
                                    this.label().subscribe(l => this.titleService.setTitle(l));
                                }
                                else {
                                    // use the default table layout
                                    this.app.getSchema('config', 'Table').subscribe(table => {
                                        this.setLayout(table.instanceLayout, 'defaulttable', null);
                                        this.value = res;
                                        this.doLayout();
                                        this.label().subscribe(l => this.titleService.setTitle(l));
                                    });
                                }
                                const contextAndValue = this.context();
                                contextAndValue.value = this.value;
>>>
                                sessionStorage.context = JSON.stringify(contextAndValue);
<<<
                            });
                        }

**Comment by uw4** [comment]
Fixed with this commit:
Handle "cache full" situation (60c52cb)
